// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace wdpr.Migrations
{
    [DbContext(typeof(KliniekContext))]
    [Migration("20220113144647_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("wdpr.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Administratie")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Client")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leeftijd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Moderator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Orthopedagoog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stagair")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Voornaam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gebruiker");
                });
#pragma warning restore 612, 618
        }
    }
}
